// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbatrmdezntfavirbxzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYXRybWRlem50ZmF2aXJieHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0OTg4MDEsImV4cCI6MjA3ODA3NDgwMX0.byFQ1pwxcseusFDp1e1B_u3HX38w3qNygaPIs4pwekI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});